### ISSUE TITLE
Compilation under Mac OS 

### ISSUE THREAD

**Issue by ratsch** [ratschlab/spladder#4]
I have smalls installed with macports and entered the proper samtools directories for bin, include and lib.
I get the following error when compiling:

~/spladder > make
echo Entering ./mex
Entering ./mex
cd mex ; make octave
/opt/local/bin/mkoctfile --mex get_reads.cpp get_reads_direct.cpp mex_input.cpp read.cpp -I/opt/local/include/bam/ -L/opt/local/lib/ -lbam -lz -lcurses
In file included from get_reads.cpp:10:
In file included from ./get_reads_direct.h:10:
/opt/local/include/bam/sam.h:28:10: fatal error: 'htslib/sam.h' file not found
#include "htslib/sam.h"
         ^
1 error generated.
make[1]: *** [get_reads.mex] Error 1
make: *** [mexfiles] Error 2

**Comment by akahles** [comment]
Which samtools version are you using. SplAdder has been successfully tested with all samtools version 0.1.x. Beginning with samtools version 1.x the code relies on htslib. I will look into this.

**Comment by akahles** [comment]
I just confirmed that the code builds under MacOS with samtools version 0.1.20. However, it will not build using any higher version of samtools as the structure of the libraries changed and now uses htslib. The workaround for now would be to use samtools <= 0.1.20. I will work on an implementation based on higher samtools versions.

**Comment by ratsch** [comment]
I confirmed it worked with samtools-0.1.19_0.darwin_14 on Mac OS X 10.10.1 and macports 2.3.3 (smalls version Version: 0.1.19-44428cd). It does not work with samtools-1.2_0.darwin_14 (smalls version 1.2 based on htslib 1.2.1) on a system with the same characteristics.

**Comment by akahles** [comment]
This is a somewhat legacy behavior, to still support the Matlab version of SplAdder. Future development will be continued on the Python branch, as this has fewer dependencies and does not rely on a samtools installation but uses the pysam package.

To reflect this better in the current repository, I will re-organize so the presence of the python code is better visible and not hidden in an extra branch.

**Comment by akahles** [comment]
I will close this for now. Please reopen, if you feel this issue has not been resolved in a sufficient way.
